//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace NatureListService.Models.CarriageDataModel {

    public partial class Carriage : XPObject {
        Train fTrain;
        [Association(@"CarriageReferencesTrain")]
        public Train Train {
            get { return fTrain; }
            set { SetPropertyValue<Train>(nameof(Train), ref fTrain, value); }
        }
        TrainIndex fTrainIndex;
        [Association(@"CarriageReferencesTrainIndex")]
        public TrainIndex TrainIndex {
            get { return fTrainIndex; }
            set { SetPropertyValue<TrainIndex>(nameof(TrainIndex), ref fTrainIndex, value); }
        }
        Station fFromStation;
        [Association(@"CarriageReferencesStation")]
        public Station FromStation {
            get { return fFromStation; }
            set { SetPropertyValue<Station>(nameof(FromStation), ref fFromStation, value); }
        }
        Station fToStation;
        [Association(@"CarriageReferencesStation1")]
        public Station ToStation {
            get { return fToStation; }
            set { SetPropertyValue<Station>(nameof(ToStation), ref fToStation, value); }
        }
        Invoice fInvoice;
        [Association(@"CarriageReferencesInvoice")]
        public Invoice Invoice {
            get { return fInvoice; }
            set { SetPropertyValue<Invoice>(nameof(Invoice), ref fInvoice, value); }
        }
        uint fPositionInTrain;
        public uint PositionInTrain {
            get { return fPositionInTrain; }
            set { SetPropertyValue<uint>(nameof(PositionInTrain), ref fPositionInTrain, value); }
        }
        uint fCarriageNumber;
        public uint CarriageNumber {
            get { return fCarriageNumber; }
            set { SetPropertyValue<uint>(nameof(CarriageNumber), ref fCarriageNumber, value); }
        }
        FreightType fFreightType;
        [Association(@"CarriageReferencesFreightType")]
        public FreightType FreightType {
            get { return fFreightType; }
            set { SetPropertyValue<FreightType>(nameof(FreightType), ref fFreightType, value); }
        }
        uint fFreightWeight;
        public uint FreightWeight {
            get { return fFreightWeight; }
            set { SetPropertyValue<uint>(nameof(FreightWeight), ref fFreightWeight, value); }
        }
        [Association(@"OperationStateReferencesCarriage")]
        public XPCollection<OperationState> OperationStates { get { return GetCollection<OperationState>(nameof(OperationStates)); } }
    }

}
