//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace NatureListService.Models.CarriageDataModel {

    public partial class OperationState : XPObject {
        Operation fOperation;
        [Association(@"OperationStateReferencesOperation")]
        public Operation Operation {
            get { return fOperation; }
            set { SetPropertyValue<Operation>(nameof(Operation), ref fOperation, value); }
        }
        DateTime fDate;
        public DateTime Date {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        Carriage fCarriage;
        [Association(@"OperationStateReferencesCarriage")]
        public Carriage Carriage {
            get { return fCarriage; }
            set { SetPropertyValue<Carriage>(nameof(Carriage), ref fCarriage, value); }
        }
        Station fStation;
        [Association(@"OperationStateReferencesStation")]
        public Station Station {
            get { return fStation; }
            set { SetPropertyValue<Station>(nameof(Station), ref fStation, value); }
        }
    }

}
