//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace NatureListService.Models.CarriageDataModel {

    public partial class Station : XPObject {
        string fName;
        public string Name {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"CarriageReferencesStation")]
        public XPCollection<Carriage> CarriagesTo { get { return GetCollection<Carriage>(nameof(CarriagesTo)); } }
        [Association(@"CarriageReferencesStation1")]
        public XPCollection<Carriage> CarriagesFrom { get { return GetCollection<Carriage>(nameof(CarriagesFrom)); } }
        [Association(@"OperationStateReferencesStation")]
        public XPCollection<OperationState> OperationStates { get { return GetCollection<OperationState>(nameof(OperationStates)); } }
    }

}
