//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace NatureListService.Models.CarriageDataModel {

    public partial class TrainIndex : XPObject {
        string fIndex;
        public string Index {
            get { return fIndex; }
            set { SetPropertyValue<string>(nameof(Index), ref fIndex, value); }
        }
        [Association(@"CarriageReferencesTrainIndex")]
        public XPCollection<Carriage> Carriages { get { return GetCollection<Carriage>(nameof(Carriages)); } }
    }

}
