//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace NatureListService.Models.Database {

    public partial class Role : XPObject {
        string fRoleName;
        public string RoleName {
            get { return fRoleName; }
            set { SetPropertyValue<string>(nameof(RoleName), ref fRoleName, value); }
        }
        [Association(@"RoleReferencesUser")]
        public XPCollection<User> Users { get { return GetCollection<User>(nameof(Users)); } }
    }

}
