//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace NatureListService.Models.Database {

    public partial class Users_Roles : XPObject {
        User fUser;
        [Association(@"Users_RolesReferencesUser")]
        public User User {
            get { return fUser; }
            set { SetPropertyValue<User>(nameof(User), ref fUser, value); }
        }
        Role fRole;
        [Association(@"Users_RolesReferencesRole")]
        public Role Role {
            get { return fRole; }
            set { SetPropertyValue<Role>(nameof(Role), ref fRole, value); }
        }
    }

}
