//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace NatureListService.Models.Database {

    public partial class User : XPObject {
        string fLogin;
        public string Login {
            get { return fLogin; }
            set { SetPropertyValue<string>(nameof(Login), ref fLogin, value); }
        }
        string fPassword;
        public string Password {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        [Association(@"RoleReferencesUser")]
        public XPCollection<Role> Roles { get { return GetCollection<Role>(nameof(Roles)); } }
    }

}
